name: Multibind tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install poetry dependencies
      run: |
        poetry install
    - name: Test with pytes
      run: |
        poetry shell
        cd tests/
        pytest
