name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ] 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install multibind with poetry
      run: |
        poetry install

    - name: Test with pytest
      run: |
        cd tests/
        poetry run pytest -v --cov=multibind --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: .
        fail_ci_if_error: ${{ github.event_name == 'pull_request' }}
        files: coverage.xml
        name: codecov-umbrella
        verbose: true
